[package]
name = "tetcoin-node-core-provisioner"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.22.3", default-features = false, features = ["alloc"] }
futures = "0.3.12"
tracing = "0.1.22"
# tracing-futures = "0.2.4"
thiserror = "1.0.23"
tetcoin-primitives = { version = "0.8.28", path = "../../../primitives" }
tetcoin-node-subsystem = { path = "../../subsystem" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util" }
futures-timer = "3.0.2"

[dev-dependencies]
tet-application-crypto = { version = "2.0.2" }
tp-keystore = { version = "0.8.1" }
