[package]
name = "tetcoin-availability-bitfield-distribution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.22"
# tracing-futures = "0.2.4"
tetsy-scale-codec = { version = "2.0.1", default-features = false, features = ["derive"] }
tetcoin-primitives = { version = "0.8.28", path = "../../../primitives" }
tetcoin-subsystem = { package = "tetcoin-node-subsystem", path = "../../subsystem" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util" }
tetcoin-node-network-protocol = { path = "../../network/protocol" }

[dev-dependencies]
tetcoin-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
bitvec = { version = "0.22.3", default-features = false, features = ["alloc"] }
tet-core = "2.0.2"
tet-application-crypto = { version = "2.0.2" }
tp-keystore = { version = "0.8.1" }
maplit = "1.0.2"
log = "0.4.13"
env_logger = "0.8.2"
assert_matches = "1.4.0"
